[package]
name = "dice_venture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.14.1", features = ["dynamic_linking"] }
bevy_replicon = "=0.27.0"
bevy_replicon_renet = "0.4.0"
clap = { version = "4.1", features = ["derive"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
serde = "1.0.209"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
